ProductionManager_EndProject/ProductionManager_EndProject/Controllers/LotController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProductionLibrary;
using ProductionManager_EndProject.Models;
using ProductionManager_EndProject.Repositories;
using System;
using System.Threading.Tasks;

namespace ProductionManager_EndProject.Controllers
{
    public class LotController : Controller
    {
        private readonly LotRepository _lotRepository;
        private readonly ProductRepository _productRepository;

        public LotController(LotRepository lotRepository, ProductRepository productRepository)
        {
            _lotRepository = lotRepository;
            _productRepository = productRepository;
        }

        [Authorize(Roles = "admin, manager, worker")]
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            LotIndexOverviewModel vm = new LotIndexOverviewModel();
            vm.Lots = _lotRepository.GetAll();
            return View(vm);
        }

        [HttpGet]
        public async Task<IActionResult> Create(int roomId, int productionId)
        {
            if (roomId == 0 || productionId == 0)
            {
                return NotFound();
            }
            LotCreateOverviewModel vm = new LotCreateOverviewModel(_productRepository);
            vm.RoomId = roomId;
            vm.ProductionId = productionId;
            return View("Create", vm);
        }


        [HttpPost]
        public async Task<IActionResult> Create(LotCreateOverviewModel model)
        {
            if (!ModelState.IsValid || model.RoomId == 0 || model.ProductId == 0)
            {
                //I can't understand why the model somehow "remember" the roomId after coming back here (in case of invalid model & model reseting),
                //but ask me to explicitly give back the productionId... Microsoft Black Magic...
                int magicNumber = model.ProductionId;
                model = new LotCreateOverviewModel(_productRepository); //We do this to repopulate the select items and here we should "forget" the roomId but Microsoft do some magic and after going back to the view the model "remember" the roomId...
                model.ProductionId = magicNumber;
                return View("Create", model);
            }
            Lot lot = new Lot();
            lot.RoomId = model.RoomId;
            lot.ProductId = (int)model.ProductId;
            lot.Description = model.Description;
            lot.StartDate = DateTime.Now;
            lot.EstimatedQuantitie = double.Parse(model.EstimatedQuantitie);
            lot.IsGrowing = true;
            lot.ProductName = await _productRepository.GetNameById((int)model.ProductId);
            lot.Reference = SetReference(lot.ProductName, lot.StartDate);
            lot.UnitType = await _productRepository.GetUnitTypeById((int)model.ProductId);

            await _lotRepository.Create(lot);

            return RedirectToAction("Units", "Production", new { id = model.ProductionId});
        }


        [NonAction]
        private string SetReference(string productName, DateTime startDate)
        {
            string reference = "";
            string[] date = startDate.ToString().Split(" ");


            if (productName.Length > 4)
            {
                for (int i = 0; i < 3; i++)
                {
                    reference += char.ToUpper(productName[i]);
                }
                reference += productName[productName.Length - 1];
            }
            else
            {
                reference += productName[0];
            }

            reference += date[0].Replace("/", "") + '-';
            reference += date[1].Replace(':', '0');
            
            return reference;
        }

        [HttpGet]
        public async Task<IActionResult> Collect(int lotId, int productionId)
        {

            if (lotId == 0 || productionId == 0)
            {
                return NotFound();
            }

            LotCollectOverviewModel vm = new LotCollectOverviewModel();
            vm.LotId = lotId;
            vm.ProductionId = productionId;

            return View(vm);


        }

        [HttpPost]
        public async Task<IActionResult> Collect(LotCollectOverviewModel model)
        {
            if (!ModelState.IsValid)
            {
                //How to show custom error without cleaning ?

                ModelState.Clear();
                ModelState.AddModelError(nameof(model.Collected), "U need to use a positive or negative number");
                return View(model);
            }
            Lot lot = await _lotRepository.GetById(model.LotId);
            lot.RecoltedQuantitie = (double)(lot.RecoltedQuantitie + model.Collected);
            double diff = 0;
            if (lot.RecoltedQuantitie < 0)
            {
                diff = -lot.RecoltedQuantitie;
                lot.RecoltedQuantitie = 0;
            }
            await _lotRepository.Update(lot);

            //Update main stock

            Product product = await _productRepository.GetById(lot.ProductId);

            if (product == null)
            {
                return NotFound();
            }
            product.RealStock += (double)(model.Collected + diff);

            await _productRepository.Update(product);

            return RedirectToAction("Units", "Production", new { id = model.ProductionId});


        }


        [Authorize(Roles = "admin, manager")]
        [HttpGet]
        public async Task<IActionResult> Delete(int lotId, int productionId)
        {
            if (lotId == 0 || productionId == 0)
            {
                return NotFound();
            }
            LotDeleteOverviewModel vm = new LotDeleteOverviewModel();
            vm.LotId = lotId;
            vm.ProductionId = productionId;

            return View(vm);

        }

        [Authorize(Roles = "admin, manager")]
        [HttpPost]
        public async Task<IActionResult> Delete(LotDeleteOverviewModel model)
        {
            if (model.LotId == 0 || model.ProductionId == 0 || model == null)
            {
                return NotFound();
            }
            Lot lot = await _lotRepository.DeleteById(model.LotId);
            if (lot == null)
            {
                return NotFound();
            }
            return RedirectToAction("Units", "Production", new {id = model.ProductionId});
        }
    }
}

ProductionManager_EndProject/ProductionManager_EndProject/Controllers/ProductionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProductionLibrary;
using ProductionManager_EndProject.Data;
using ProductionManager_EndProject.Models;
using ProductionManager_EndProject.Repositories;

namespace ProductionManager_EndProject.Controllers
{

    [Authorize(Roles = "admin, manager, worker")]
    public class ProductionController : Controller
    {
        private readonly ProductionRepository _productionRepository;
        private readonly UserManager<User> _userManager;


        public ProductionController(ProductionRepository productionRepository, UserManager<User> userManager)
        {
            _productionRepository = productionRepository;
            _userManager = userManager;
        }

        [HttpGet]
        public async Task<IActionResult> Selection()
        {
            ProductionSelectionOverview vm = new ProductionSelectionOverview();
            vm.AvaiableProductions = _productionRepository.GetAll();
            return View(vm);
        }

        [HttpGet]
        public async Task<IActionResult> MainPage(int id)
        {
            Production activeProd = await _productionRepository.GetByIdInclusive(id);
            //ProductionMainPageOverviewModel vm = new ProductionMainPageOverviewModel();
            if (activeProd != null)
            {
                return View(activeProd);
            }
            return NotFound();
            
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var x = _productionRepository.GetAll();
            return View(x);
        }
        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var production = await _productionRepository.GetById(id);
            if (production == null)
            {
                return NotFound();
            }

            return View(production);
        }

        public async Task<IActionResult> Units(int id)
        {
            Production activeProd = await _productionRepository.GetByIdWithUnits(id);
            //ProductionMainPageOverviewModel vm = new ProductionMainPageOverviewModel();
            if (activeProd != null)
            {
                return View(activeProd);
            }
            return NotFound();
        }

        
        public async Task<IActionResult> Missions(int id)
        {
            Production activeProd = await _productionRepository.GetByIdWithTasks(id);
            //ProductionMainPageOverviewModel vm = new ProductionMainPageOverviewModel();
            if (activeProd != null)
            {
                return View(activeProd);
            }
            return NotFound();
        }
        [Authorize(Roles = "admin, manager")]
        public async Task<IActionResult> ManagerPanel(int id)
        {
            Production activeProd = await _productionRepository.GetByIdWithTasks(id);
            //ProductionMainPageOverviewModel vm = new ProductionMainPageOverviewModel();
            if (activeProd != null)
            {
                return View(activeProd);
            }
            return NotFound();
        }

        [Authorize(Roles = "admin, manager")]
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }

        [Authorize(Roles = "admin, manager")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Production production)
        {
            if (ModelState.IsValid)
            {
                var result = await _productionRepository.Create(production);
                if (result != null)
                {
                    return RedirectToAction("Selection");
                }
                ModelState.AddModelError(nameof(production.ProductionName), "This name is already used !");
            }
            return View(production);
        }

        [Authorize(Roles = "admin, manager")]
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var production = await _productionRepository.GetById(id);
            if (production == null)
            {
                return NotFound();
            }
            return View(production);
        }

        [Authorize(Roles = "admin, manager")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Production production)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _productionRepository.Update(production);
                }
                catch
                {

                    throw;

                }
                return RedirectToAction("Index");
            }
            return View(production);
        }

        [Authorize(Roles = "admin, manager")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var production = await _productionRepository.GetById(id);
            if (production == null)
            {
                return NotFound();
            }

            return View(production);
        }

        [Authorize(Roles = "admin, manager")]
        // POST: Production/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _productionRepository.DeleteById(id);
            return RedirectToAction("Index");
        }

    }
}

ProductionManager_EndProject/ProductionManager_EndProject/Controllers/RoomController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ProductionLibrary;
using ProductionManager_EndProject.Models;
using ProductionManager_EndProject.Repositories;
using System.Threading.Tasks;

namespace ProductionManager_EndProject.Controllers
{
    [Authorize(Roles = "admin, manager")]
    public class RoomController : Controller
    {
        private readonly RoomRepository _roomRepository;
        private readonly UserManager<User> _userManager;


        public RoomController(RoomRepository roomRepository, UserManager<User> userManager)
        {
            _roomRepository = roomRepository;
            _userManager = userManager;
        }


        [HttpGet]
        public async Task<IActionResult> Create(int productionId) 
        {
            Room room = new Room();
            room.ProductionId = productionId;

            return View(room);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Room room)
        {

            if (ModelState.IsValid)
            {
                var result = await _roomRepository.Create(room);
                if (result != null)
                {

                    return RedirectToAction("Units", "Production", new { id = room.ProductionId});
                }
                ModelState.AddModelError(nameof(room.RoomName), "U already have a unit with this name");
            }
            return View(room);
        }


        
        [HttpGet]
        public async Task<IActionResult> Delete(int id, int prodId)
        {
            DeleteRoomOverviewModel vm = new DeleteRoomOverviewModel();
            vm.RoomId = id;
            vm.ProductionId = prodId;
            return View(vm);
        }
        

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletePost(DeleteRoomOverviewModel vm)
        {
            var target = await _roomRepository.DeleteById(vm.RoomId);
            return RedirectToAction("Units", "Production", new {id = target.ProductionId});

        }
    }
}

ProductionManager_EndProject/ProductionManager_EndProject/Views/Production/Create.cshtml
@model ProductionLibrary.Production

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Production</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductionName" class="control-label"></label>
                <input asp-for="ProductionName" class="form-control" />
                <span asp-validation-for="ProductionName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Country" class="control-label"></label>
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ZIP" class="control-label"></label>
                <input asp-for="ZIP" class="form-control" />
                <span asp-validation-for="ZIP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Street" class="control-label"></label>
                <input asp-for="Street" class="form-control" />
                <span asp-validation-for="Street" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Number" class="control-label"></label>
                <input asp-for="Number" class="form-control" />
                <span asp-validation-for="Number" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProductionManager_EndProject/ProductionManager_EndProject/Views/Production/Delete.cshtml
@model ProductionLibrary.Production

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Production</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductionName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductionName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Country)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ZIP)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ZIP)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Street)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Street)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Number)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Number)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ProductionManager_EndProject/ProductionManager_EndProject/Views/Production/MainPage.cshtml
@using Microsoft.AspNetCore.Identity
@using ProductionLibrary
@inject UserManager<User> userManager

@*@{
    }*@
@model Production

<div class="topnav mb-3">
  <a  class="active" asp-controller="Production" asp-action="MainPage" asp-route-id="@Model.Id">Overview</a>
  <a asp-controller="Production" asp-action="Units" asp-route-id="@Model.Id" >Units</a>
  <a asp-controller="Production" asp-action="Missions" asp-route-id="@Model.Id" >Missions</a>
  <a asp-controller="Production" asp-action="ManagerPanel" asp-route-id="@Model.Id" >Manager Panel</a>
</div>



<h4 class="title-box my-4">Welcome to @Model.ProductionName</h4>
<h2 class="subtitle-box">@Model.ProductionName's units:</h2>

@if (Model.Rooms.Count() == 0)
{
    <h3 class="warning-box">U need to create your first unit</h3>

    <a asp-controller="Room" asp-action="Create" asp-route-productionId="@Model.Id" class="btn btn-blue">New Unit</a>

}
else
{
    foreach (var room in Model.Rooms)
    {

        <table class="table mb-0">
            <thead class="thead-dark">
                <tr>
                    <th style="text-align: left; vertical-align: middle;" width="20%">@room.RoomName (@room.Lots.Count())</th>
                    <th>
                        <div style="display: flex; justify-content: space-between;">
                        <a asp-controller="Lot" asp-action="Create" asp-route-roomId="@room.Id" asp-route-productionId="@room.ProductionId" class="btn btn-blue">Add lot</a>
                        <a asp-controller="Room" asp-action="Delete" asp-route-id="@room.Id" asp-route-prodId="@room.ProductionId" class="btn btn-red">X</a>
                        </div>
                    </th>
                </tr>
            </thead>
        </table>
        if (room.Lots.Count() == 0)
        {
            <table class="table">
                <thead class="bg-danger">
                    <tr>
                        <th>@room.RoomName is empty</th>
                    </tr>
                </thead>
            </table>
        }
        else
        {
            <table class="table table-bordered">
                <thead class="bg-secondary">
                    <tr>
                        <th width="20%">Lot Reference</th>
                        <th width="20%">Product</th>
                        <th width="20%">Estimation</th>
                        <th width="20%">Recolted</th>
                        <th width="20%">Options</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var lot in room.Lots)
                    {
                        <tr class="bg-primary">
                            <td>@lot.Reference</td>
                            <td>@lot.ProductName</td>
                            <td>@lot.EstimatedQuantitie (@lot.UnitType)</td>
                            <td>@lot.RecoltedQuantitie (@lot.UnitType)</td>
                            <td>
                                <div style="display: flex; justify-content: space-between;">
                                    <a asp-controller="Lot" asp-action="Collect" asp-route-lotId="@lot.Id" asp-route-productionId="@Model.Id" class="btn btn-green">Collect</a>
                                    <a asp-controller="Lot" asp-action="Delete" asp-route-lotId="@lot.Id" asp-route-productionId="@Model.Id" class="btn btn-red">X</a>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
    }
    <a asp-controller="Room" asp-action="Create" asp-route-productionId="@Model.Id" class="btn btn-blue">Create new unit</a>
}
<hr />
<h2 class="subtitle-box">@Model.ProductionName's missions</h2>
@if (Model.ProdTasks.Where(p => p.ProdTaskStatusId == 1 || p.ProdTaskStatusId == 2).Count() == 0)
{
    <h3 class="warning-box">No avaiable missions curently</h3>
    <a asp-controller="ProdTask" asp-action="Create" asp-route-productionId="@Model.Id" class="btn btn-blue">New Mission</a>
}
else
{
    <table class="table table-bordered mt-2">
        <thead>
            <tr>
                <th width="100%" class="h2 text-center border-white border-top-0 coltitle">Avaiable missions(@Model.ProdTasks.Where(t => t.ProdTaskStatusId == 1 && t.ProductionId == Model.Id).Count())</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="bg-primary">
                    @foreach (var prodTask in Model.ProdTasks.OrderBy(p => p.ProdTaskStatusId).Where(t => (t.ProdTaskStatusId == 1 || t.ProdTaskStatusId == 2) && t.ProductionId == Model.Id))
                    {
                        if (prodTask.ProdTaskStatusId == 1)
                        {

                            <div class="card border bodyground my-2 bg-warning" width="100%">
                                <div class="card-body">
                                    <h5 class="card-title">@prodTask.TaskName</h5>
                                    <hr>
                                    <pre readonly class="card-text">@prodTask.TaskDescription</pre>
                                    <hr>
                                    <h5 style="color: blue">Assigned:</h5>
                                    
                                        <div class="new-task">New Task !</div>
                                    <hr>
                                    <a asp-controller="ProdTask" asp-action="AssignProdTask" asp-route-id="@prodTask.Id" asp-route-productionId="@Model.Id" class="btn btn-blue mt-4">Take Mission</a>
                                </div>
                            </div>
                        }
                        else
                        {
                            <div class="card border bodyground my-2" width="100%">
                                <div class="card-body">
                                    <h5 class="card-title">@prodTask.TaskName</h5>
                                    <hr>
                                    <pre readonly class="card-text">@prodTask.TaskDescription</pre>
                                    <hr>
                                    <h5 style="color: blue">Assigned:</h5>
                                    @foreach (var prodTaskUsers in prodTask.ProdTaskUsers.Where(p => p.ProdTaskId == prodTask.Id))
                                    {
                                        <div class="assigned mt-3">@prodTaskUsers.UserName</div>
                                    }

                                    @{
                                        var t = prodTask.ProdTaskUsers.Where(p => p.ProdTaskId == prodTask.Id && p.UserId == @userManager.GetUserId(User));
                                    }
                                    <hr>
                                    @if (t.Count() == 0)
                                    {
                                        <a asp-controller="ProdTask" asp-action="AssignProdTask" asp-route-id="@prodTask.Id" asp-route-productionId="@Model.Id" class="btn btn-blue mt-4">Take Mission</a>
                                    }
                                    else
                                    {
                                        <a asp-controller="ProdTask" asp-action="AssignProdTask" asp-route-id="@prodTask.Id" asp-route-productionId="@Model.Id" class="btn btn-red mt-4">Remove Mission</a>
                                    }
                                    @if (t.Count() != 0)
                                   {
                                    <a asp-controller="ProdTask" asp-action="FinishTask" asp-route-id="@prodTask.Id" asp-route-productionId="@Model.Id" class="btn btn-green mt-4 ml-3">Mission completed</a>                                       
                                   }
                                </div>
                            </div>
                        }
                    }
                </td>

            </tr>
        </tbody>
    </table>

    <a asp-controller="ProdTask" asp-action="Create" asp-route-productionId="@Model.Id" class="btn btn-blue">New Mission</a>
}

ProductionManager_EndProject/ProductionManager_EndProject/Views/Production/Units.cshtml
@using Microsoft.AspNetCore.Identity
@using ProductionLibrary
@inject UserManager<User> userManager

@*@{
    }*@
@model Production

<div class="topnav mb-3">
    <a asp-controller="Production" asp-action="MainPage" asp-route-id="@Model.Id">Overview</a>
    <a asp-controller="Production" asp-action="Units" asp-route-id="@Model.Id" class="active">Units</a>
    <a asp-controller="Production" asp-action="Missions" asp-route-id="@Model.Id">Missions</a>
    <a asp-controller="Production" asp-action="ManagerPanel" asp-route-id="@Model.Id">Manager Panel</a>
</div>

<h2 class="subtitle-box">@Model.ProductionName's units:</h2>

@if (Model.Rooms.Count() == 0)
{
    <h3 class="warning-box">U need to create your first unit</h3>

    <a asp-controller="Room" asp-action="Create" asp-route-productionId="@Model.Id" class="btn btn-blue">New Unit</a>

}
else
{
    foreach (var room in Model.Rooms)
    {

        <table class="table mb-0">
            <thead class="thead-dark">
                <tr>
                    <th style="text-align: left; vertical-align: middle;" width="20%">@room.RoomName (@room.Lots.Count())</th>
                    <th>
                        <div style="display: flex; justify-content: space-between;">
                            <a asp-controller="Lot" asp-action="Create" asp-route-roomId="@room.Id" asp-route-productionId="@room.ProductionId" class="btn btn-blue">Add lot</a>
                            <a asp-controller="Room" asp-action="Delete" asp-route-id="@room.Id" asp-route-prodId="@room.ProductionId" class="btn btn-red">X</a>
                        </div>
                    </th>
                </tr>
            </thead>
        </table>
        if (room.Lots.Count() == 0)
        {
            <table class="table">
                <thead class="bg-danger">
                    <tr>
                        <th>@room.RoomName is empty</th>
                    </tr>
                </thead>
            </table>
        }
        else
        {
            <table class="table table-bordered">
                <thead class="bg-secondary">
                    <tr>
                        <th width="20%">Lot Reference</th>
                        <th width="20%">Product</th>
                        <th width="20%">Estimation</th>
                        <th width="20%">Recolted</th>
                        <th width="20%">Options</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var lot in room.Lots)
                    {
                        <tr class="bg-primary">
                            <td>@lot.Reference</td>
                            <td>@lot.ProductName</td>
                            <td>@lot.EstimatedQuantitie (@lot.UnitType)</td>
                            <td>@lot.RecoltedQuantitie (@lot.UnitType)</td>
                            <td>
                                <div style="display: flex; justify-content: space-between;">
                                    <a asp-controller="Lot" asp-action="Collect" asp-route-lotId="@lot.Id" asp-route-productionId="@Model.Id" class="btn btn-green">Collect</a>
                                    <a asp-controller="Lot" asp-action="Delete" asp-route-lotId="@lot.Id" asp-route-productionId="@Model.Id" class="btn btn-red">X</a>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
    }
    <a asp-controller="Room" asp-action="Create" asp-route-productionId="@Model.Id" class="btn btn-blue">Create new unit</a>
}